---

    name: Build Image
    on: [workflow_dispatch]
    
    jobs:
      build-image:
        name: Build image on Self hosted runner
        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v3

        - name: Setup build environment
          run: |
            mkdir -p .config/containers
            (echo '[storage]';echo 'driver = "vfs"') > .config/containers/storage.conf
            buildah info
    
        - name: Build Image
          uses: redhat-actions/buildah-build@v2
          env:
            BUILDAH_ISOLATION: chroot
          with:
            image: test-image
            containerfiles: Dockerfile
    
    