---

    name: Build Image
    on: [workflow_dispatch]
    
    jobs:
      build-image:
        name: Build image on Self hosted runner
        runs-on: self-hosted
    
        steps:
        - uses: actions/checkout@v3

        - name: Debugging
          run: | 
            echo "github:1001:2147483646" > /etc/subuid
            echo "github:1001:2147483646" > /etc/subgid
    
        - name: Build Image
          uses: redhat-actions/buildah-build@v2
          env:
            BUILDAH_ISOLATION: chroot
          with:
            image: test-image
            containerfiles: Dockerfile
            extra-args: --storage-driver=vfs
    
    